// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLq_2mmPNzh09-YXKPrRDwAlI21Debh3U',
    appId: '1:489411029598:web:148531fe97f4988629a2cf',
    messagingSenderId: '489411029598',
    projectId: 'reddit-b5106',
    authDomain: 'reddit-b5106.firebaseapp.com',
    storageBucket: 'reddit-b5106.appspot.com',
    measurementId: 'G-E5N786LX72',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBD-lMhlLnJN7VvDFxZcly8QVbN-Y_AS2s',
    appId: '1:489411029598:android:f207a29e7eb42d0029a2cf',
    messagingSenderId: '489411029598',
    projectId: 'reddit-b5106',
    storageBucket: 'reddit-b5106.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAzGnO5CtPaaxnUgJsHi_n70qtgOLRFt0',
    appId: '1:489411029598:ios:7b335acb5136f03929a2cf',
    messagingSenderId: '489411029598',
    projectId: 'reddit-b5106',
    storageBucket: 'reddit-b5106.appspot.com',
    iosBundleId: 'com.example.reddit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAzGnO5CtPaaxnUgJsHi_n70qtgOLRFt0',
    appId: '1:489411029598:ios:02005bcfd51101f829a2cf',
    messagingSenderId: '489411029598',
    projectId: 'reddit-b5106',
    storageBucket: 'reddit-b5106.appspot.com',
    iosBundleId: 'com.example.reddit.RunnerTests',
  );
}
